### ISSUE TITLE
Surfacing to-be-written content on site

### ISSUE THREAD

**Issue by patio11** [CAVaccineInventory/site#140]
Problem statement: Our site serves many audiences. The primary one is and always will be vaccine seekers. But as of Day 8, where we are not a household name, it has to quickly bootstrap an understanding of how we operate and why we are likely to be legitimate that a vaccine seeker may not need or particularly care about either way.

e.g. from Zoelle

> Hi folks! Sorry to jump into an active conversation, but just wanted to note that I'm starting to see signs that the Department of Health may be (off the record, and thus not openly) calling into question whether we're a website you can trust when reached for comment - any work we can do to boost credibility, emphasize that we get our information from medical professionals, etc, seems worth prioritizing if possible

At some point, soon, we would like to have a content piece which decisively kills that objection, but it needs somewhere to live. If you can create the place for it to live, and lorem ipsum it out, I can get three paragraphs written very, very quickly.

I anticipate 3~5 similar pieces to start.

It also might make sense to merge the notion of that and the notion of the "If you are a ..." on our current Who We Are page, if that helps inform thinking.

**Comment by eliblock** [comment]
Closing all issues: https://blog.vaccinateca.com/vaccinate-the-states-is-winding-down
