### ISSUE TITLE
Creative way to unblock tech people volunteering

### ISSUE THREAD

**Issue by patio11** [CAVaccineInventory/site#141]
Login with Github -> Airtable form with options for type of volunteering, explicitly call out that phone banking is most helpful right now -> if phone banking immediately give email Discord link which we refresh daily manually. (To avoid it leaking.) If not, collect contact info and say "Thanks for registering your interest. The project is growing quickly, etc etc, we'll be in touch."

Bury it; not navigable on the site. I distribute via Twitter. 

This would allow us to onboard _many_ semi-trusted volunteers w/o making it obvious we were excluding people (for good reasons but for ones which might not feel good to the excluded), and would solve our phonebank problem ~instantly for the next few days until the call center comes online.

**Comment by eliblock** [comment]
Closing all issues: https://blog.vaccinateca.com/vaccinate-the-states-is-winding-down
