### ISSUE TITLE
Filtering/Bubbling up County specific info on near by page

### ISSUE THREAD

**Issue by skalnik** [CAVaccineInventory/site#142]
A lot of county vaccine distribution sites limit to county residence only. It'd be great if the Near By page could take the inputted zip/geolocated coordinate, figure out the county from that, and bubble up sites in that county before a site that may be closer but less relevant.

@obra brought this up in Discord and may have some additional thoughts!

**Comment by eliblock** [comment]
Closing all issues: https://blog.vaccinateca.com/vaccinate-the-states-is-winding-down
