### ISSUE TITLE
Render more with Jekyll and less with Javascript

### ISSUE THREAD

**Issue by skalnik** [CAVaccineInventory/site#159]
Splitting this out of https://github.com/CAVaccineInventory/site/issues/119 we have some thoughts of maybe rendering more information with Jekyll, and less with JS. I'm a big fan of this idea, and would love to see this happen.

I think part of what we'll need is more individual feeds of data, though we could probably do some processing and split it apart as part of the ingestion process. However, it also seems like some of that split up work is in progress over at https://github.com/CAVaccineInventory/airtable-export/pull/13.

I'm not super well versed with this, but @phildini is a Jekyll expert and may have more thoughts on how this should/could function though!

**Comment by eliblock** [comment]
Closing all issues: https://blog.vaccinateca.com/vaccinate-the-states-is-winding-down
