### ISSUE TITLE
Display provider/network information inline for sites that are associated with one

### ISSUE THREAD

**Issue by nschiefer** [CAVaccineInventory/site#179]
We maintain detailed notes on various networked providers (like Kaiser and Sutter). We suspect that most users don't see this, so it would be nice to display this inline with the sites that are associated with a network.

In particular, we sometimes receive conflicting information from "corporate" and individual sites. We would like users to see all of the information that we have when considering the site.

**Comment by eliblock** [comment]
Closing all issues: https://blog.vaccinateca.com/vaccinate-the-states-is-winding-down
