### ISSUE TITLE
Disable reporting Sentry errors for 3rd-party JS

### ISSUE THREAD

**Issue by ebroder** [CAVaccineInventory/site#194]
There are a handful of errors in Sentry that are coming from (e.g.) the guts of the Google Maps JS. We're not going to be able to do anything useful with those errors (they're probably a mix of "bugs in Google Maps" and "bugs in people's Chrome extensions").

We can configure Sentry to ignore 3rd-party errors; we should do that so that Sentry reporting remains high signal.

**Comment by eliblock** [comment]
Closing all issues: https://blog.vaccinateca.com/vaccinate-the-states-is-winding-down
