### ISSUE TITLE
Be able to easily link to individual sites on listing pages

### ISSUE THREAD

**Issue by skalnik** [CAVaccineInventory/site#204]
From @obra:
> Anchors on individual sites on our listings pages. I wanted to point out an issue with data on SAFEWAY PHARMACY #1483 and realized I can't link to it via https://www.vaccinateca.com/regions/bay_area.html#something

**Comment by eliblock** [comment]
Closing all issues: https://blog.vaccinateca.com/vaccinate-the-states-is-winding-down
