### ISSUE TITLE
Do we want to bring back "✅ In Your County"

### ISSUE THREAD

**Issue by skalnik** [CAVaccineInventory/site#215]
Many sites are limited to only residents of a specific county. When we updated the card design, we lost the small check box that called this out. Maybe that's ok, maybe not!

Pros:
- Super clear a site is in your county
- Ensures we set people up for maximum success

Cons:
- A bit of noise for sites that don't have this restriction
- We showed it based on search location, so it wasn't necessarily correct (i.e. when searched in another zip)

**Comment by eliblock** [comment]
Closing all issues: https://blog.vaccinateca.com/vaccinate-the-states-is-winding-down
