### ISSUE TITLE
Add Vaccination Site Placeholders before content loads

### ISSUE THREAD

**Issue by skalnik** [CAVaccineInventory/site#229]
As part of reviewing the map on near by page stuff, @shajith pointed out we see some reflows happen when content loads in. This is to be expected since there's suddenly content that loads in after the initial page load, but this isn't ideal. It'd be great if we could add a placeholder for some sites as we load the content so the page feels more stable.

**Comment by eliblock** [comment]
Closing all issues: https://blog.vaccinateca.com/vaccinate-the-states-is-winding-down
