### ISSUE TITLE
Improve VoiceOver support

### ISSUE THREAD

**Issue by shajith** [CAVaccineInventory/site#254]
I knocked around the website using voiceover, and found some issues, primarily tested on the near-me results page. Two that might be high value to address, for screen-reader users:

* Tabbing to the results takes a few keypresses. The typical solution is a "skip to content" link.
* There's nothing in the header of each search result that you can tab into, so voiceover skips to the links inside each search result instead of announcing the name of the place. Creating a reasonable tab order for elements inside each search result cell would solve this, no need to do anything specific for voiceover support.

**Comment by eliblock** [comment]
Closing all issues: https://blog.vaccinateca.com/vaccinate-the-states-is-winding-down
