### ISSUE TITLE
Add maps to County pages

### ISSUE THREAD

**Issue by skalnik** [CAVaccineInventory/site#281]
County pages are still heavily used, Los Angeles seeing more hits than the "Near Me" page. A nice user enhancement we should consider is adding maps to the county pages. The initial objection we had to this was perhaps it'd be strange if the user panned their map outside of the county, but @Manishearth pointed out that we could just have a nice county overlay that makes this relatively clear.

**Comment by eliblock** [comment]
Closing all issues: https://blog.vaccinateca.com/vaccinate-the-states-is-winding-down
