### ISSUE TITLE
Mismatches between the near-me and county pages

### ISSUE THREAD

**Issue by shajith** [CAVaccineInventory/site#304]
The near-me and county pages are both reached from the front page with very similar interactions: typing in something into the autocomplete (or invoking geolocation) and clicking "Find Vaccine". 

Example near-me page: https://www.vaccinateca.com/near-me?zip=94085
Example county page: https://www.vaccinateca.com/counties/santa_clara

They are very different pages though. Material to the "show me a list of sites" interaction, these are the differences:

* The county page does not have a search form, or a selector to switch between Sites with reported doses, Sites we have contacted, and all known sites. This thing: ![image](https://user-images.githubusercontent.com/91915/106397603-32fac580-63c3-11eb-88e7-1c5703334ab0.png)
* The county page lists sites with reported vaccine, sites without reported vaccine, and sites we haven't contacted, in one continuous list.
* The county page doesn't have a map yet. There is #281 adding one to that page.
* Minor: the in-page title on the near-me pages say "Vaccination Sites Near You", while  county pages simply prints the name of the county up top.

This issue was created to list the known differences somewhere, so we can ask and answer questions like: Should we change anything about the county or near-me pages to address these differences? Are these conscious design choices we want to retain?

**Comment by eliblock** [comment]
Closing all issues: https://blog.vaccinateca.com/vaccinate-the-states-is-winding-down
