### ISSUE TITLE
Audit 3rd party APIs required by the site

### ISSUE THREAD

**Issue by cavaccineinv** [CAVaccineInventory/site#347]
Please list the 3rd party APIs required for the site to work.

For each API, check (or delegate) that:
* We still need to use this API.
* It makes sense to consume as an API, rather than bundled data.
* We have appropriate handling and timeouts and so on in the face of failures.

**Comment by eliblock** [comment]
Closing all issues: https://blog.vaccinateca.com/vaccinate-the-states-is-winding-down
