### ISSUE TITLE
We should consider having a message at the top of the search-by-zipcode results pointing you to the county page

### ISSUE THREAD

**Issue by obra** [CAVaccineInventory/site#382]
https://discord.com/channels/799147121357881364/803734598936821830/809632063468208150

As many sites are restricted by county, we might want to provide guidance at the top of the map search page recommending that they also consult the county page for the county including that zip code.

**Comment by eliblock** [comment]
Closing all issues: https://blog.vaccinateca.com/vaccinate-the-states-is-winding-down
