### ISSUE TITLE
County policy page filtering should update URL

### ISSUE THREAD

**Issue by skalnik** [CAVaccineInventory/site#409]
The old county policy page would change the URL when a user filtered. We lost that when we moved to the airtable-less views. We should bring that back!

The only URLs looked like `https://www.vaccinateca.com/county-policies#Alameda_County` so ideally we could replicate that.

**Comment by eliblock** [comment]
Closing all issues: https://blog.vaccinateca.com/vaccinate-the-states-is-winding-down
