### ISSUE TITLE
Provide a thumbs up/thumbs down vote on location data quality

### ISSUE THREAD

**Issue by cavaccineinv** [CAVaccineInventory/site#440]
Provide thumbs up/down votes on each location, for data accuracy. It is safe to assume that the vast majority of people aren't filing correction reports, and the absence of reports can mean either "this is good info" or "not many people are checking this location out".

The exact language would need some workshopping, to make sure that most votes align with the specific yes/no signal we're trying to get. For example, people interpret a downvote as "I couldn't get a vaccine here" regardless of information accuracy.

Collect this data, and use it internally to flag locations that need to be double checked. We won't display this data, to prevent trolls from steering viewers.

CC @obra

**Comment by eliblock** [comment]
Closing all issues: https://blog.vaccinateca.com/vaccinate-the-states-is-winding-down
