### ISSUE TITLE
Remove dependencies on " County" county name suffixes

### ISSUE THREAD

**Issue by cavaccineinv** [CAVaccineInventory/site#462]
We've noticed that county names are inconsistent (most end in " County" with the odd exception like San Francisco). This is unfortunately for a lot of pragmatic things, e.g. it requires some hacks in the scraper.

We'd appreciate it if the website could remove any explicit assumptions about the " County" suffix, so we can remove it from the database. This goes for the locations API, and counties API.

Noticed uses:
* [ ] https://github.com/CAVaccineInventory/site/blob/6d913cd6a365c42152286eb8585fa304ef172729/webpack/counties.js

**Comment by eliblock** [comment]
Closing all issues: https://blog.vaccinateca.com/vaccinate-the-states-is-winding-down
