### ISSUE TITLE
Need to show more eligibility/restriction criteria

### ISSUE THREAD

**Issue by shajith** [CAVaccineInventory/site#463]
We recently added a few new tags to the list available to phone-bankers to pick from.

* Yes: appointments full
* Scheduling second dose only
* Vaccinating essential workers

We don't currently surface the information captured by these tags on the site cards on the website. We probably should.

This information is sometimes repeated in the free-text public notes written by the phone-banker.

This is the site card at the moment, for context:

<img width="1219" alt="image" src="https://user-images.githubusercontent.com/91915/108026162-acf29780-6fdc-11eb-8452-7fa35c3b5087.png">

**Comment by eliblock** [comment]
Closing all issues: https://blog.vaccinateca.com/vaccinate-the-states-is-winding-down
