### ISSUE TITLE
Add link to API docs from About page

### ISSUE THREAD

**Issue by skalnik** [CAVaccineInventory/site#551]
Our API is a great thing we should be as public about as possible. A link to the docs from the about page could help visibility and I don't think it'd hurt anything.

Discord where this was mentioned: https://discord.com/channels/799147121357881364/802069867813273640/815108213724282921

**Comment by eliblock** [comment]
Closing all issues: https://blog.vaccinateca.com/vaccinate-the-states-is-winding-down
