### ISSUE TITLE
Vaccination Site Location Card redesign

### ISSUE THREAD

**Issue by skalnik** [CAVaccineInventory/site#574]
There's some discussion about redesigning the "Cards" we use to represent locations! I took some notes of things to consider from what we have now:

Information to add:
- Availability info
  - This includes if appointments are known to be available
- Vaccine types
- Represent info coming from data feeds or phone calls
- Better county and provider chain info on the cards
- Designed with possible links to VaccineFinder and/or Google Maps

Additionally, we should be thinking about smaller screen sizes, our cards are almost never at their originally designed width right now. Between most of our users on mobile or with medium displays having cards next to the map, the cards are generally rather narrow.

**Comment by eliblock** [comment]
Closing all issues: https://blog.vaccinateca.com/vaccinate-the-states-is-winding-down
