### ISSUE TITLE
make map & list know about each other

### ISSUE THREAD

**Issue by rhkeeler** [CAVaccineInventory/site#656]
right now it's hard to match up a results card with a location on the map. We should make it so
* if you click on a map pin, we autoscroll the list to the relevant results card
  * bonus: emphasize the right results card (thin border, maybe?)
* if you click on a results card (anywhere that is not otherwise linkified), we highlight or emphasize the relevant map pin
  * honestly, better would be if you mouse over a results card, but I'm fine with whatever is easiest
  * for "highlight or emphasize" -- again, I'm down for whatever is easiest. Some ideas: display the in-map info modal for the location (as if you had clicked on the pin); add a thick border around the right pin; invert the colors of the right pin; make the right pin larger (1.5x the size, maybe?)

**Comment by eliblock** [comment]
Closing all issues: https://blog.vaccinateca.com/vaccinate-the-states-is-winding-down
