### ISSUE TITLE
searching by county should go to the map + filters results page

### ISSUE THREAD

**Issue by rhkeeler** [CAVaccineInventory/site#661]
If someone searches by county from the main page, we should send them to the results page with the map and filters, not the county list. 

We should also make the county info links more prominent -- something like:
<img width="916" alt="Screen Shot 2021-03-30 at 11 00 32 AM" src="https://user-images.githubusercontent.com/19540645/113035760-7f634700-9161-11eb-984d-80cd5b87f68b.png">

Not super-picky on how we choose which county info pages to display -- any counties that have results in the results list seems sufficient to me; we could also show nearby counties.

**Comment by eliblock** [comment]
Closing all issues: https://blog.vaccinateca.com/vaccinate-the-states-is-winding-down
