### ISSUE TITLE
collapse results that book together into the same card

### ISSUE THREAD

**Issue by rhkeeler** [CAVaccineInventory/site#677]
Right now, for a lot of zip codes, the results list on the left is dominated by network provider cards (e.g. pharmacies). AFAICT, for most of these, the booking process isn't actually location dependent -- you search for appointments across all CVSs or Safeways or w/e -- so each additional card clutters up the list without giving you an additional thing to try. We should keep them on the map, of course, but collapse the results to only show one card.

Instead of showing the address, we can show "11 in your area".

**Comment by eliblock** [comment]
Closing all issues: https://blog.vaccinateca.com/vaccinate-the-states-is-winding-down
