### ISSUE TITLE
`Share Link` w/o zip doesn't report error to user

### ISSUE THREAD

**Issue by skalnik** [CAVaccineInventory/site#887]
@alexmv pointed out that https://sentry.io/organizations/vaccinateca/issues/2329297043 is rather noisy is Sentry. I dug into it and this results when a user hits a <kbd>Share Link</kbd> button on a location without a zip code. I noticed that there's no real user feedback that this didn't work.

Ideally we could just hide the button in that case. It may be confusing as to why some sites are missing the button, but it'd be less confusing than a broken button. Alternatively, at minimum, we should at least show some sort of "Unable to Copy" error in the button.

**Comment by eliblock** [comment]
Closing all issues: https://blog.vaccinateca.com/vaccinate-the-states-is-winding-down
