### ISSUE TITLE
[embed] change search button styling

### ISSUE THREAD

**Issue by rhkeeler** [CAVaccineInventory/site#895]
make the search action(s) more clear in https://github.com/CAVaccineInventory/site/pull/891. in descending order of preference, but open to choosing based on ease of implementation.

1. replace the "locations near me" button with a "Near me" dropdown from the text entry field (like on vaccinateca.com). 
  a. it's okay if the option disappears as soon as someone starts typing
  b. ideally we would then have an explicit Search button, instead of automatically taking action upon an address selection. (button should be the round green style.)
2. find a bullseye/crosshairs icon we have permission to use and make it the button that searches "near me"
  a. could put it on the right-hand side of the search box (fading out when you start typing, maybe, ideally?)
  b. could put it in the bottom right corner a la google
3. bring back the explicit Search button, and have two buttons right next to each other. (buttons should, alas, be the round green style.)

**Comment by eliblock** [comment]
Closing all issues: https://blog.vaccinateca.com/vaccinate-the-states-is-winding-down
