### ISSUE TITLE
Prettify error messages

### ISSUE THREAD

**Issue by alexcole** [CAVaccineInventory/site#905]
Currently we have a couple of error messages that use `alert(...)` to generate an ugly pop up. We should redesign these to be less jarring to the user. 

Ones that I know of:
- Failure to detect current location (if the user denies location access) on homepage, /near-me, and /embed
- Failure to find a place on /embed (https://github.com/CAVaccineInventory/site/pull/891)

Perhaps we can mimic the UI pattern used to render the "Please enter a valid zip code" error on /near-me and use it in these places too?

**Comment by eliblock** [comment]
Closing all issues: https://blog.vaccinateca.com/vaccinate-the-states-is-winding-down
